apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: examples
spec:
  dnsNames:
    # The following values need to contain the actual namespace you are deploying to;
    # replace "examples" with your desired namespace
    - "federation-server-0.federation-nodes.examples"
  secretName: tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
