apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
    - "federation-server-0.federation-nodes.default"
  secretName: tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
