apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: custom-configuration
  annotations:
    rabbitmq.com/version: "4.3"
spec:
  image: rabbitmq:4.3-management
  replicas: 1
  rabbitmq:
    additionalConfig: |
      log.console.level = debug
