apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: mtls
  annotations:
    rabbitmq.com/version: "4.3"
spec:
  image: rabbitmq:4.3-management
  replicas: 1
  tls:
    secretName: tls-secret
    caSecretName: ca-secret
