version: 2

multi-ecosystem-groups:
  gomod:
    schedule:
      interval: "daily"

updates:
- package-ecosystem: "gomod"
  directory: "/"
  patterns:
  - '*'
  ignore:
    - dependency-name: "k8s.io/api"
      versions: ["0.19.x"]
    - dependency-name: "k8s.io/api-machinery"
      versions: ["0.19.x"]
    - dependency-name: "k8s.io/client-go"
      versions: ["0.19.x"]
    - dependency-name: "github.com/go-logr/logr"
      versions: ["0.2.x"]
  multi-ecosystem-group: "gomod"
- package-ecosystem: "gomod"
  directory: "/kubectl-rabbitmq/"
  patterns:
  - '*'
  ignore:
    - dependency-name: "github.com/rabbitmq/cluster-operator/v2"
  multi-ecosystem-group: "gomod"
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    actions:
      patterns:
      - '*'
  schedule:
    interval: "weekly"
