apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: self-signed-cert
spec:
  secretName: self-signed-cert
  isCA: true
  dnsNames:
  - rabbitmqcluster-sample-rabbitmq-ingress
  issuerRef:
    name: selfsigned-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    group: cert-manager.io
