apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: pod-anti-affinity
  annotations:
    rabbitmq.com/version: "4.3"
spec:
  image: rabbitmq:4.3-management
  replicas: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - pod-anti-affinity
          topologyKey: kubernetes.io/hostname
