apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: vault-tls
  annotations:
    rabbitmq.com/version: "4.3"
spec:
  image: rabbitmq:4.3-management
  secretBackend:
    vault:
      role: rabbitmq
      tls:
        pkiIssuerPath: pki/issue/cert-issuer
