// +build !ignore_autogenerated

/* Copyright (c) 2020 VMware, Inc. or its affiliates.  All rights reserved.

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/. */

// Code generated by controller-gen. DO NOT EDIT.

package status

import (
	"k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAvailableConditionManager) DeepCopyInto(out *ClusterAvailableConditionManager) {
	*out = *in
	in.condition.DeepCopyInto(&out.condition)
	if in.endpoints != nil {
		in, out := &in.endpoints, &out.endpoints
		*out = new(v1.Endpoints)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAvailableConditionManager.
func (in *ClusterAvailableConditionManager) DeepCopy() *ClusterAvailableConditionManager {
	if in == nil {
		return nil
	}
	out := new(ClusterAvailableConditionManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqClusterCondition) DeepCopyInto(out *RabbitmqClusterCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqClusterCondition.
func (in *RabbitmqClusterCondition) DeepCopy() *RabbitmqClusterCondition {
	if in == nil {
		return nil
	}
	out := new(RabbitmqClusterCondition)
	in.DeepCopyInto(out)
	return out
}
