# RabbitMQ Cluster Operator
#
# Copyright 2020 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Mozilla Public license, Version 2.0 (the "License").  You may not use this product except in compliance with the Mozilla Public License.
#
# This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
images:
- name: rabbitmqoperator/cluster-operator-dev
  newName: ghcr.io/rabbitmq/cluster-operator
  newTag: latest
resources:
- ../namespace/base/
- ../crd/
- ../rbac/
- ../manager/
- ../webhook
- ../certmanager
- metrics_service.yaml

patches:
- path: manager_webhook_patch.yaml
  target:
    kind: Deployment

replacements:
- source:
    kind: Service
    version: v1
    name: webhook-service
    fieldPath: .metadata.name
  targets:
  - select:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert
    fieldPaths:
    - .spec.dnsNames.0
    - .spec.dnsNames.1
    options:
      delimiter: '.'
      index: 0
      create: true
- source:
    kind: Service
    version: v1
    name: webhook-service
    fieldPath: .metadata.namespace
  targets:
  - select:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert
    fieldPaths:
    - .spec.dnsNames.0
    - .spec.dnsNames.1
    options:
      delimiter: '.'
      index: 1
      create: true
- source:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert
    fieldPath: .metadata.namespace
  targets:
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
    - .metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: '/'
      index: 0
      create: true
- source:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert
    fieldPath: .metadata.name
  targets:
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
    - .metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: '/'
      index: 1
      create: true
