# This example is GKE specific, other Kubernetes deployments will have a different `storageClass` for SSD disks.
#
# https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/ssd-pd
# https://cloud.google.com/compute/docs/disks/performance#ssd_persistent_disk
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

