apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
type: Opaque
data:
  # Generate using `printf "%s" "$(pwgen 20 1)" | base64`
  erlang-cookie: dGhvaTNnaWV5YWU3dGlUNnF1aXY=
