# RabbitMQ Cluster Operator
#
# Copyright 2020 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Mozilla Public license, Version 2.0 (the "License").  You may not use this product except in compliance with the Mozilla Public License.
#
# This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.
#

name: rabbitmq-operator
version: 0.3
appVersion: 0.7.0-build.41
description: Pivotal RabbitMQ for Kubernetes
keywords:
- rabbitmq
- operator
- message queue
- AMQP
home: https://pivotal.io/rabbitmq
icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
maintainers:
- name: Pivotal
  email: rabbitmq-for-k8s@pivotal.com
engine: gotpl
