# Copyright (c) 2020 VMware, Inc. or its affiliates.  All rights reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: rabbitmq-operator
version: 0.3
appVersion: 0.7.0-build.41
description: Pivotal RabbitMQ for Kubernetes
keywords:
- rabbitmq
- operator
- message queue
- AMQP
home: https://pivotal.io/rabbitmq
icon: https://bitnami.com/assets/stacks/rabbitmq/img/rabbitmq-stack-220x234.png
maintainers:
- name: Pivotal
  email: rabbitmq-for-k8s@pivotal.com
engine: gotpl
