apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: mtls-inter-node
spec:
  image: rabbitmq:4.3.4-management
  replicas: 3
  tls:
    interNode:
      enabled: true
      issuerRef:
        name: mtls-inter-node-ca-issuer
        kind: Issuer
        group: cert-manager.io
