// Code generated by counterfeiter. DO NOT EDIT.
package resourcegeneratorfakes

import (
	"sync"

	generator "github.com/pivotal/rabbitmq-for-kubernetes/pkg/internal/resourcegenerator"
)

type FakeResourceGenerator struct {
	BuildStub        func(generator.GenerationContext) ([]generator.TargetResource, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 generator.GenerationContext
	}
	buildReturns struct {
		result1 []generator.TargetResource
		result2 error
	}
	buildReturnsOnCall map[int]struct {
		result1 []generator.TargetResource
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResourceGenerator) Build(arg1 generator.GenerationContext) ([]generator.TargetResource, error) {
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 generator.GenerationContext
	}{arg1})
	fake.recordInvocation("Build", []interface{}{arg1})
	fake.buildMutex.Unlock()
	if fake.BuildStub != nil {
		return fake.BuildStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.buildReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeResourceGenerator) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *FakeResourceGenerator) BuildCalls(stub func(generator.GenerationContext) ([]generator.TargetResource, error)) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *FakeResourceGenerator) BuildArgsForCall(i int) generator.GenerationContext {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	argsForCall := fake.buildArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeResourceGenerator) BuildReturns(result1 []generator.TargetResource, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 []generator.TargetResource
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceGenerator) BuildReturnsOnCall(i int, result1 []generator.TargetResource, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 []generator.TargetResource
			result2 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 []generator.TargetResource
		result2 error
	}{result1, result2}
}

func (fake *FakeResourceGenerator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResourceGenerator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ generator.ResourceGenerator = new(FakeResourceGenerator)
