# RabbitMQ Cluster Operator
#
# Copyright 2020 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Mozilla Public license, Version 2.0 (the "License").  You may not use this product except in compliance with the Mozilla Public License.
#
# This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.

template: |
  local clientFilterFunc(j) = std.length(std.findSubstr("rabbitmq-client", j.name)) > 0;
  local clientService = std.filter(clientFilterFunc, $.services)[0];
  local secretFilterFunc(j) = std.length(std.findSubstr("rabbitmq-admin", j.name)) > 0;
  local admin = std.filter(secretFilterFunc, $.secrets);

  local vhost = "%2F";
  local ingress = if clientService.spec.type == "LoadBalancer" then
      if std.objectHas(clientService.status.loadBalancer.ingress[0], "hostname") then
        clientService.status.loadBalancer.ingress[0].hostname
      else
        clientService.status.loadBalancer.ingress[0].ip
    else
      clientService.spec.clusterIP;
  local adminUsername = admin[0].data['username'];
  local adminPassword = admin[0].data['password'];
  local mgmtURI = "http://" + ingress + ":15672/#/login/" + adminUsername + "/" + adminPassword;
  local apiURI = "http://" + adminUsername + ":" + adminPassword + "@" + ingress + ":15672/api/";
  local amqpURI = "amqp://" + adminUsername + ":" + adminPassword + "@" + ingress + "/" + vhost;
  {
    "hostname": ingress,
    "username": adminUsername,
    "password": adminPassword,
    "dashboard_url": mgmtURI,
    "hostnames": [
      ingress
    ],
    "http_api_uri": apiURI,
    "http_api_uris": [
      apiURI
    ],
    "ssl": false,
    "uri": amqpURI,
    "uris": [
      amqpURI
    ],
    "vhost": vhost,
    "protocols": {
      "amqp": {
        "host": ingress,
        "hosts": [
          ingress
        ],
        "password": adminPassword,
        "port": 5672,
        "ssl": false,
        "uri": amqpURI,
        "uris": [
          amqpURI
        ],
        "username": adminUsername,
        "vhost": vhost
      },
      "management": {
        "host": ingress,
        "hosts": [
          ingress
        ],
        "password": adminPassword,
        "path": "/api/",
        "port": 15672,
        "ssl": false,
        "uri": apiURI,
        "uris": [
          apiURI
        ],
        "username": adminUsername
      }
    },
  }
