template: |
  local ingressFilterFunc(j) = std.length(std.findSubstr("rabbitmq-ingress", j.name)) > 0;
  local ingressService = std.filter(ingressFilterFunc, $.services)[0];
  local secretFilterFunc(j) = std.length(std.findSubstr("rabbitmq-admin", j.name)) > 0;
  local admin = std.filter(secretFilterFunc, $.secrets);

  local vhost = "%2F";
  local ingress = if ingressService.spec.type == "LoadBalancer" then
      if std.objectHas(ingressService.status.loadBalancer.ingress[0], "hostname") then
        ingressService.status.loadBalancer.ingress[0].hostname
      else
        ingressService.status.loadBalancer.ingress[0].ip
    else
      ingressService.spec.clusterIP;
  local adminUsername = admin[0].data['username'];
  local adminPassword = admin[0].data['password'];
  local mgmtURI = "http://" + ingress + ":15672/#/login/" + adminUsername + "/" + adminPassword;
  local apiURI = "http://" + adminUsername + ":" + adminPassword + "@" + ingress + ":15672/api/";
  local amqpURI = "amqp://" + adminUsername + ":" + adminPassword + "@" + ingress + "/" + vhost;
  {
    "hostname": ingress,
    "username": adminUsername,
    "password": adminPassword,
    "dashboard_url": mgmtURI,
    "hostnames": [
      ingress
    ],
    "http_api_uri": apiURI,
    "http_api_uris": [
      apiURI
    ],
    "ssl": false,
    "uri": amqpURI,
    "uris": [
      amqpURI
    ],
    "vhost": vhost,
    "protocols": {
      "amqp": {
        "host": ingress,
        "hosts": [
          ingress
        ],
        "password": adminPassword,
        "port": 5672,
        "ssl": false,
        "uri": amqpURI,
        "uris": [
          amqpURI
        ],
        "username": adminUsername,
        "vhost": vhost
      },
      "management": {
        "host": ingress,
        "hosts": [
          ingress
        ],
        "password": adminPassword,
        "path": "/api/",
        "port": 15672,
        "ssl": false,
        "uri": apiURI,
        "uris": [
          apiURI
        ],
        "username": adminUsername
      }
    },
  }
