# Copyright (c) 2020 VMware, Inc. or its affiliates.  All rights reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

resources:
- certificate.yaml

# the following config is for teaching kustomize how to do var substitution
vars:
- name: CERTIFICATENAME
  objref:
    kind: Certificate
    group: certmanager.k8s.io
    version: v1alpha1
    name: serving-cert # this name should match the one in certificate.yaml
- name: CERTIFICATENAMESPACE
  objref:
    kind: Certificate
    group: certmanager.k8s.io
    version: v1alpha1
    name: serving-cert # this name should match the one in certificate.yaml
  fieldref:
    fieldpath: metadata.namespace

configurations:
- kustomizeconfig.yaml
