# Copyright (c) 2020 VMware, Inc. or its affiliates.  All rights reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# This configuration is for teaching kustomize how to update name ref and var substitution 
nameReference:
- kind: Issuer
  group: certmanager.k8s.io
  fieldSpecs:
  - kind: Certificate
    group: certmanager.k8s.io
    path: spec/issuerRef/name

varReference:
- kind: Certificate
  group: certmanager.k8s.io
  path: spec/commonName
- kind: Certificate
  group: certmanager.k8s.io
  path: spec/dnsNames
