// Code generated by counterfeiter. DO NOT EDIT.
package rabbitmqclientfakes

import (
	"sync"

	"github.com/rabbitmq/cluster-operator/internal/rabbitmqclient"
)

type FakeSecretStoreClient struct {
	ReadCredentialsStub        func(string) (string, string, error)
	readCredentialsMutex       sync.RWMutex
	readCredentialsArgsForCall []struct {
		arg1 string
	}
	readCredentialsReturns struct {
		result1 string
		result2 string
		result3 error
	}
	readCredentialsReturnsOnCall map[int]struct {
		result1 string
		result2 string
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSecretStoreClient) ReadCredentials(arg1 string) (string, string, error) {
	fake.readCredentialsMutex.Lock()
	ret, specificReturn := fake.readCredentialsReturnsOnCall[len(fake.readCredentialsArgsForCall)]
	fake.readCredentialsArgsForCall = append(fake.readCredentialsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ReadCredentialsStub
	fakeReturns := fake.readCredentialsReturns
	fake.recordInvocation("ReadCredentials", []interface{}{arg1})
	fake.readCredentialsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeSecretStoreClient) ReadCredentialsCallCount() int {
	fake.readCredentialsMutex.RLock()
	defer fake.readCredentialsMutex.RUnlock()
	return len(fake.readCredentialsArgsForCall)
}

func (fake *FakeSecretStoreClient) ReadCredentialsCalls(stub func(string) (string, string, error)) {
	fake.readCredentialsMutex.Lock()
	defer fake.readCredentialsMutex.Unlock()
	fake.ReadCredentialsStub = stub
}

func (fake *FakeSecretStoreClient) ReadCredentialsArgsForCall(i int) string {
	fake.readCredentialsMutex.RLock()
	defer fake.readCredentialsMutex.RUnlock()
	argsForCall := fake.readCredentialsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSecretStoreClient) ReadCredentialsReturns(result1 string, result2 string, result3 error) {
	fake.readCredentialsMutex.Lock()
	defer fake.readCredentialsMutex.Unlock()
	fake.ReadCredentialsStub = nil
	fake.readCredentialsReturns = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSecretStoreClient) ReadCredentialsReturnsOnCall(i int, result1 string, result2 string, result3 error) {
	fake.readCredentialsMutex.Lock()
	defer fake.readCredentialsMutex.Unlock()
	fake.ReadCredentialsStub = nil
	if fake.readCredentialsReturnsOnCall == nil {
		fake.readCredentialsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
			result3 error
		})
	}
	fake.readCredentialsReturnsOnCall[i] = struct {
		result1 string
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSecretStoreClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.readCredentialsMutex.RLock()
	defer fake.readCredentialsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSecretStoreClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ rabbitmqclient.SecretStoreClient = new(FakeSecretStoreClient)
