#!/bin/bash
set -eu

main() {
  local cluster_name="${1?cluster name must be specified}"
  local namespace="${2?-namespace must be specified}"

  expected_replicas=$(kubectl --namespace=$namespace get statefulsets.apps "$cluster_name"  -o json | jq .spec.replicas)
  echo "Waiting for ${expected_replicas} node(s) of the ${cluster_name} cluster to become available..."
  for i in {1..180}; do
    ready_replicas=$(kubectl --namespace=$namespace get statefulsets.apps "$cluster_name"  -o json | jq .status.readyReplicas)
    if [[ ${ready_replicas} == ${expected_replicas} ]]; then
      echo "done"
      exit 0
    fi
    echo "- ${ready_replicas} replicas ready"
    sleep 5
  done

  echo "Timed out"
  exit 1
}

main "$@"
