/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	rabbitmqv1beta1 "github.com/pivotal/rabbitmq-for-kubernetes/pkg/apis/rabbitmq/v1beta1"
	versioned "github.com/pivotal/rabbitmq-for-kubernetes/pkg/client/clientset/versioned"
	internalinterfaces "github.com/pivotal/rabbitmq-for-kubernetes/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/pivotal/rabbitmq-for-kubernetes/pkg/client/listers/rabbitmq/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RabbitmqClusterInformer provides access to a shared informer and lister for
// RabbitmqClusters.
type RabbitmqClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.RabbitmqClusterLister
}

type rabbitmqClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRabbitmqClusterInformer constructs a new informer for RabbitmqCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRabbitmqClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRabbitmqClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRabbitmqClusterInformer constructs a new informer for RabbitmqCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRabbitmqClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RabbitmqV1beta1().RabbitmqClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RabbitmqV1beta1().RabbitmqClusters(namespace).Watch(options)
			},
		},
		&rabbitmqv1beta1.RabbitmqCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *rabbitmqClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRabbitmqClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rabbitmqClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rabbitmqv1beta1.RabbitmqCluster{}, f.defaultInformer)
}

func (f *rabbitmqClusterInformer) Lister() v1beta1.RabbitmqClusterLister {
	return v1beta1.NewRabbitmqClusterLister(f.Informer().GetIndexer())
}
