apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: sample
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                volumeMounts:
                  - name: additional-disk
                    mountPath: /var/lib/log
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: persistence
              namespace: rabbitmq-system
             labels:
                "app.kubernetes.io/name": "sample"
            spec:
              storageClassName: standard
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 3Gi
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: persistence-foo
              namespace: rabbitmq-system
              labels:
                "app.kubernetes.io/name": "sample"
            spec:
              storageClassName: standard
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
