apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: examples
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: examples
spec:
  dnsNames:
    - "*.tls-nodes.examples.svc.cluster.local"
    - "*.tls.examples.svc.cluster.local"
    - "*.tls.examples.svc"
    - "*.examples.pod"
    - "*.examples.pod.cluster.local"
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
