apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
    - "*.tls-nodes.examples.svc.cluster.local"
  secretName: tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
