apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: tls
spec:
  replicas: 1
  tls:
    secretName: tls-secret
    disableNonTLSListeners: true
    # This example uses a self-signed certificate, so the CA certificate is the same as the server certificate
    caSecretName: tls-secret
