#!/bin/bash

set -ex

helm package .

helm template rabbitmq-0.1.tgz -f plans/example-configurations.yaml > template-output

# expected-template-output is generated by running helm template rabbitmq-0.1.tgz -f plans/example-configurations.yaml > expected-template-output
# it should be updated if we add any new configurations and when we modify plans/example-configurations.yaml
diff template-output expected-template-output
