name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install Kind via Makefile
        run: |
          make kind yj
          echo "$PWD/bin" >> "$GITHUB_PATH"

      - name: Running Test e2e
        run: make test-e2e
