# This action updates operator version, CRD, and clusterrole in our helm chart
# For more information see https://github.com/rabbitmq-pro/tanzu-rabbitmq-operator-chart
name: update_helm_chart

on:
  push:
    branches:
    - action_to_sync_helm_chart
    
  workflow_dispatch:

jobs:
    create-chart-pr:
        name: Create pull request to char repo
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Checkout helm repo
          uses: actions/checkout@v4
          with:
            repository: DanielePalaia/test
            #token: ${{ secrets.GIT_HUB_INFRA_REPO_ACCESS_TOKEN }}
            path: ./tanzu-rabbitmq-operator-chart

        - name: Update helm released version and CRD
          run: |   
            BUNDLE_VERSION=${GITHUB_REF#refs/*/} 
            BUNDLE_VERSION=${BUNDLE_VERSION:1}
            cd ./tanzu-rabbitmq-operator-chart
            git config --global user.name "rabbitmqclusteroperator"
            git config --global user.email "rabbitmq@dependanbot.com"
            git branch update_crd_and_version
            git checkout update_crd_and_version
            cp ./../config/crd/bases/rabbitmq.com_rabbitmqclusters.yaml ./crds/rabbitmq-cluster/
            sed -i  's/cluster-operator:.*/cluster-operator:0.0.0/' ./Chart.yaml
            python3 ./scripts/update_cluster_operator_clusterrole.py ./scripts/generators/rabbitmq-cluster-operator/clusterrole.yml ./scripts/generators/rabbitmq-cluster-operator/clusterrole-generator.yml 
            python3 ./scripts/update_cluster_operator_value_version.py ./values.yaml "rabbitmqoperator/cluster-operator" 0.0.0
            cp ./scripts/generators/rabbitmq-cluster-operator/clusterrole-generator.yml  ./templates/cluster-operator/clusterrole.yaml 
            git checkout ./scripts/generators/rabbitmq-cluster-operator/clusterrole-generator.yml
            git add .
            git commit -m "Updating RabbitMQ cluster operator version and CRD"

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6





            