#@ load("@ytt:data", "data")

---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cool-catalog
  #! Subscriptions cannot install operators provided by CatalogSources
  #! that are not in the same namespace unless the CatalogSource is
  #! created in the olm namespace.
  #! https://olm.operatorframework.io/docs/troubleshooting/subscription/#a-subscription-in-namespace-x-cant-install-operators-from-a-catalogsource-in-namespace-y
  namespace: ns-1
spec:
  sourceType: grpc
  image: #@ data.values.image
  displayName: Test catalog
  publisher: RabbitMQ Test
  updateStrategy:
    registryPoll:
      interval: 10m
